#############################################################################
# Makefile for building: dirview
# Generated by qmake (3.1) (Qt 5.11.0)
# Project:  dirview.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile dirview.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I../../../../mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = dirview1.0.0
DISTDIR = /usr/lib/x86_64-linux-gnu/qt5/examples/widgets/itemviews/dirview/.tmp/dirview1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../../../../mkspecs/features/spec_pre.prf \
		../../../../mkspecs/common/unix.conf \
		../../../../mkspecs/common/linux.conf \
		../../../../mkspecs/common/sanitize.conf \
		../../../../mkspecs/common/gcc-base.conf \
		../../../../mkspecs/common/gcc-base-unix.conf \
		../../../../mkspecs/common/g++-base.conf \
		../../../../mkspecs/common/g++-unix.conf \
		../../../../mkspecs/qconfig.pri \
		../../../../mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../mkspecs/modules/qt_lib_concurrent.pri \
		../../../../mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../mkspecs/modules/qt_lib_core.pri \
		../../../../mkspecs/modules/qt_lib_core_private.pri \
		../../../../mkspecs/modules/qt_lib_dbus.pri \
		../../../../mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../mkspecs/modules/qt_lib_gui.pri \
		../../../../mkspecs/modules/qt_lib_gui_private.pri \
		../../../../mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../mkspecs/modules/qt_lib_network.pri \
		../../../../mkspecs/modules/qt_lib_network_private.pri \
		../../../../mkspecs/modules/qt_lib_opengl.pri \
		../../../../mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../mkspecs/modules/qt_lib_printsupport.pri \
		../../../../mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../mkspecs/modules/qt_lib_sql.pri \
		../../../../mkspecs/modules/qt_lib_sql_private.pri \
		../../../../mkspecs/modules/qt_lib_testlib.pri \
		../../../../mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../mkspecs/modules/qt_lib_widgets.pri \
		../../../../mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../mkspecs/modules/qt_lib_xml.pri \
		../../../../mkspecs/modules/qt_lib_xml_private.pri \
		../../../../mkspecs/features/qt_functions.prf \
		../../../../mkspecs/features/qt_config.prf \
		../../../../mkspecs/linux-g++/qmake.conf \
		../../../../mkspecs/features/spec_post.prf \
		../../../../mkspecs/features/exclusive_builds.prf \
		../../../../mkspecs/features/toolchain.prf \
		../../../../mkspecs/features/default_pre.prf \
		../../../../mkspecs/features/resolve_config.prf \
		../../../../mkspecs/features/default_post.prf \
		../../../../mkspecs/features/qml_debug.prf \
		../../../../mkspecs/features/warn_on.prf \
		../../../../mkspecs/features/qt.prf \
		../../../../mkspecs/features/resources.prf \
		../../../../mkspecs/features/moc.prf \
		../../../../mkspecs/features/unix/opengl.prf \
		../../../../mkspecs/features/uic.prf \
		../../../../mkspecs/features/unix/thread.prf \
		../../../../mkspecs/features/qmake_use.prf \
		../../../../mkspecs/features/file_copies.prf \
		../../../../mkspecs/features/testcase_targets.prf \
		../../../../mkspecs/features/exceptions.prf \
		../../../../mkspecs/features/yacc.prf \
		../../../../mkspecs/features/lex.prf \
		dirview.pro  main.cpp
QMAKE_TARGET  = dirview
DESTDIR       = 
TARGET        = dirview


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dirview.pro ../../../../mkspecs/linux-g++/qmake.conf ../../../../mkspecs/features/spec_pre.prf \
		../../../../mkspecs/common/unix.conf \
		../../../../mkspecs/common/linux.conf \
		../../../../mkspecs/common/sanitize.conf \
		../../../../mkspecs/common/gcc-base.conf \
		../../../../mkspecs/common/gcc-base-unix.conf \
		../../../../mkspecs/common/g++-base.conf \
		../../../../mkspecs/common/g++-unix.conf \
		../../../../mkspecs/qconfig.pri \
		../../../../mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../mkspecs/modules/qt_lib_concurrent.pri \
		../../../../mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../mkspecs/modules/qt_lib_core.pri \
		../../../../mkspecs/modules/qt_lib_core_private.pri \
		../../../../mkspecs/modules/qt_lib_dbus.pri \
		../../../../mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../mkspecs/modules/qt_lib_gui.pri \
		../../../../mkspecs/modules/qt_lib_gui_private.pri \
		../../../../mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../mkspecs/modules/qt_lib_network.pri \
		../../../../mkspecs/modules/qt_lib_network_private.pri \
		../../../../mkspecs/modules/qt_lib_opengl.pri \
		../../../../mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../mkspecs/modules/qt_lib_printsupport.pri \
		../../../../mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../mkspecs/modules/qt_lib_sql.pri \
		../../../../mkspecs/modules/qt_lib_sql_private.pri \
		../../../../mkspecs/modules/qt_lib_testlib.pri \
		../../../../mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../mkspecs/modules/qt_lib_widgets.pri \
		../../../../mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../mkspecs/modules/qt_lib_xml.pri \
		../../../../mkspecs/modules/qt_lib_xml_private.pri \
		../../../../mkspecs/features/qt_functions.prf \
		../../../../mkspecs/features/qt_config.prf \
		../../../../mkspecs/linux-g++/qmake.conf \
		../../../../mkspecs/features/spec_post.prf \
		../../../../mkspecs/features/exclusive_builds.prf \
		../../../../mkspecs/features/toolchain.prf \
		../../../../mkspecs/features/default_pre.prf \
		../../../../mkspecs/features/resolve_config.prf \
		../../../../mkspecs/features/default_post.prf \
		../../../../mkspecs/features/qml_debug.prf \
		../../../../mkspecs/features/warn_on.prf \
		../../../../mkspecs/features/qt.prf \
		../../../../mkspecs/features/resources.prf \
		../../../../mkspecs/features/moc.prf \
		../../../../mkspecs/features/unix/opengl.prf \
		../../../../mkspecs/features/uic.prf \
		../../../../mkspecs/features/unix/thread.prf \
		../../../../mkspecs/features/qmake_use.prf \
		../../../../mkspecs/features/file_copies.prf \
		../../../../mkspecs/features/testcase_targets.prf \
		../../../../mkspecs/features/exceptions.prf \
		../../../../mkspecs/features/yacc.prf \
		../../../../mkspecs/features/lex.prf \
		dirview.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile dirview.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../../../mkspecs/features/spec_pre.prf:
../../../../mkspecs/common/unix.conf:
../../../../mkspecs/common/linux.conf:
../../../../mkspecs/common/sanitize.conf:
../../../../mkspecs/common/gcc-base.conf:
../../../../mkspecs/common/gcc-base-unix.conf:
../../../../mkspecs/common/g++-base.conf:
../../../../mkspecs/common/g++-unix.conf:
../../../../mkspecs/qconfig.pri:
../../../../mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../mkspecs/modules/qt_lib_concurrent.pri:
../../../../mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../mkspecs/modules/qt_lib_core.pri:
../../../../mkspecs/modules/qt_lib_core_private.pri:
../../../../mkspecs/modules/qt_lib_dbus.pri:
../../../../mkspecs/modules/qt_lib_dbus_private.pri:
../../../../mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../../mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../../mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../mkspecs/modules/qt_lib_glx_support_private.pri:
../../../../mkspecs/modules/qt_lib_gui.pri:
../../../../mkspecs/modules/qt_lib_gui_private.pri:
../../../../mkspecs/modules/qt_lib_input_support_private.pri:
../../../../mkspecs/modules/qt_lib_kms_support_private.pri:
../../../../mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../../mkspecs/modules/qt_lib_network.pri:
../../../../mkspecs/modules/qt_lib_network_private.pri:
../../../../mkspecs/modules/qt_lib_opengl.pri:
../../../../mkspecs/modules/qt_lib_opengl_private.pri:
../../../../mkspecs/modules/qt_lib_openglextensions.pri:
../../../../mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../mkspecs/modules/qt_lib_printsupport.pri:
../../../../mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../mkspecs/modules/qt_lib_service_support_private.pri:
../../../../mkspecs/modules/qt_lib_sql.pri:
../../../../mkspecs/modules/qt_lib_sql_private.pri:
../../../../mkspecs/modules/qt_lib_testlib.pri:
../../../../mkspecs/modules/qt_lib_testlib_private.pri:
../../../../mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../mkspecs/modules/qt_lib_widgets.pri:
../../../../mkspecs/modules/qt_lib_widgets_private.pri:
../../../../mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../mkspecs/modules/qt_lib_xml.pri:
../../../../mkspecs/modules/qt_lib_xml_private.pri:
../../../../mkspecs/features/qt_functions.prf:
../../../../mkspecs/features/qt_config.prf:
../../../../mkspecs/linux-g++/qmake.conf:
../../../../mkspecs/features/spec_post.prf:
../../../../mkspecs/features/exclusive_builds.prf:
../../../../mkspecs/features/toolchain.prf:
../../../../mkspecs/features/default_pre.prf:
../../../../mkspecs/features/resolve_config.prf:
../../../../mkspecs/features/default_post.prf:
../../../../mkspecs/features/qml_debug.prf:
../../../../mkspecs/features/warn_on.prf:
../../../../mkspecs/features/qt.prf:
../../../../mkspecs/features/resources.prf:
../../../../mkspecs/features/moc.prf:
../../../../mkspecs/features/unix/opengl.prf:
../../../../mkspecs/features/uic.prf:
../../../../mkspecs/features/unix/thread.prf:
../../../../mkspecs/features/qmake_use.prf:
../../../../mkspecs/features/file_copies.prf:
../../../../mkspecs/features/testcase_targets.prf:
../../../../mkspecs/features/exceptions.prf:
../../../../mkspecs/features/yacc.prf:
../../../../mkspecs/features/lex.prf:
dirview.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile dirview.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h ../../../../mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/widgets/itemviews/dirview || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/widgets/itemviews/dirview
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/widgets/itemviews/dirview/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/widgets/itemviews/dirview/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/widgets/itemviews/dirview/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

